welcomeMessages:
  - "&7%player% &fвпервые зашёл на сервер, приветствуем!"
  - "&7%player% &fвпервые присоединился к нам, добро пожаловать!"
joinMessages:
  - "&7%player% &fзалетел на сервер"
  - "&7%player% &fприскакал на сервер"
  - "&7%player% &fпришёл к нам с пиццей"
quitMessages:
  - "&7%player% &fпокинул нас"
  - "&7%player% &fвышел с сервера"
  - "&7%player% &fвыбежал с сервера"